version: '3.3'

services:
    jenkins:
        build:
            context: "."
        ports:
            - "8080:8080"
        volumes:
            # - jenkins_home:/var/jenkins_home
            - ./my_marvin.yml:/var/jenkins_conf
        environment: 
            - CASC_JENKINS_CONFIG=/var/jenkins_conf/
            - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
            - USER_NASSO_PASSWORD=root
            - USER_I_DONT_KNOW_PASSWORD=root
            - USER_VAUGIE_G_PASSWORD=root
            - USER_CHOCOLATEEN_PASSWORD=admin

volumes:
    jenkins_home:
